version: '3.8'

services:
  moviesapi:
    build:
      context: .
      dockerfile: MoviesApi/Dockerfile
    container_name: moviesapi
    depends_on:
      - elasticsearch
    environment:
      - ConnectionStrings__DefaultConnection=Server=host.docker.internal,1433;Database=MoviesApiDb;User Id=sa;Password=YourStrong!Passw0rd;Encrypt=False;TrustServerCertificate=True;
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "5000:80"
    restart: always
    volumes:
      - ./logs:/app/logs

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - ELASTIC_PASSWORD=elasticpassword
    ports:
      - "9200:9200"
    volumes:
      - elastic_data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.7.0
    container_name: kibana
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"

volumes:
  elastic_data:
